# Generated by Django 2.0.1 on 2018-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='积分'),
        ),
    ]
